<?php

declare(strict_types=1);

namespace App\Modules\Pipeline\Models;

use App\Core\Models\BaseModel;
use App\Modules\Pipeline\Enums\ReminderChannel;
use App\Modules\Pipeline\Enums\ReminderState;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * An auto-generated nudge for a due/overdue next action (or task). Generated by
 * the hourly sweep and delivered by the per-minute dispatcher.
 */
class Reminder extends BaseModel
{
    use HasFactory;

    protected $fillable = [
        'next_action_id', 'task_id', 'remind_at', 'channel', 'sent_at', 'state',
    ];

    protected function casts(): array
    {
        return array_merge(parent::casts(), [
            'remind_at' => 'datetime',
            'sent_at' => 'datetime',
            'channel' => ReminderChannel::class,
            'state' => ReminderState::class,
        ]);
    }

    public function nextAction(): BelongsTo
    {
        return $this->belongsTo(NextAction::class);
    }

    public function task(): BelongsTo
    {
        return $this->belongsTo(Task::class);
    }

    public function scopePending(Builder $query): Builder
    {
        return $query->where('state', ReminderState::Pending->value);
    }

    /** Pending reminders whose time has come. */
    public function scopeDue(Builder $query): Builder
    {
        return $query->where('state', ReminderState::Pending->value)
            ->where('remind_at', '<=', now());
    }
}
